"""Trading Bot V6 Professional
Version: 6.0.0
"""
import os
APP_NAME="Trading Bot V6 Professional"
VERSION="6.0.0"
DEBUG_MODE=os.getenv("DEBUG_MODE","true").lower()=="true"
BINANCE_BASE_URL="https://api.binance.com"
TIMEFRAME="15m"
CANDLE_LIMIT=500
REQUEST_TIMEOUT=15
RETRY_COUNT=3
SCAN_INTERVAL=30
INITIAL_BALANCE=1000.0
RISK_PER_TRADE=0.02
TRADING_FEE=0.0004
SLIPPAGE=0.0002
MAX_OPEN_POSITIONS=2
COOLDOWN_CANDLES=4
EMA_FAST=7
EMA_MID=25
EMA_SLOW=50
EMA_TREND=200
RSI_PERIOD=14
ATR_PERIOD=14
VWAP_PERIOD=20
SUPERTREND_PERIOD=10
SUPERTREND_MULTIPLIER=3.0
MIN_VOLUME_RATIO=1.2
TREND_STRENGTH_THRESHOLD=25
MARKET_SCORE_THRESHOLD=80
CONFIDENCE_THRESHOLD=80
MAX_CONSECUTIVE_LOSSES=5
MAX_DAILY_LOSS_PERCENT=5.0
TELEGRAM_TOKEN=os.getenv("TELEGRAM_TOKEN","")
TELEGRAM_CHAT_ID=os.getenv("TELEGRAM_CHAT_ID","")
JOURNAL_FILE="journal.csv"
LEARNING_LOG_FILE="learning_log.csv"
LOG_LEVEL="DEBUG" if DEBUG_MODE else "INFO"
